# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestValidator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

   pod 'ValidatorSdk'
 # pod 'ValidatorSdk', :path => '../EmailValidator'

  # Pods for TestValidator

end
